### Testing in the Jupyter Notebook view

***

#### Task 1

We need to create a function that we call 'counts' that will take a list as an input and returns a dictionary as a result. 
In this disctionary, we need to be able to see the unique items that were input, and the number of times each unique item was counted. 
___

In [8]:
def counts(list):
    # this is where the important part is
    dictionary = {}
    
    for letter in list:
        if letter in dictionary:
            dictionary[letter] += 1
        else:
            dictionary[letter] = 1
            
    return dictionary

we need to set up the logic

need a disctionary whose values always start at 0

loop until no more items in the list
    take next item in list
    check if item is alreadu in dictionary
        yes?
            add one to vlaue associated with key
        no?
            put item in dictionary as key
            add 1 to value of that key
     put item in dictionary as key
     add 1 to value of that key
end loop

In [35]:
counts(['A', 'A', 'B', 'C', 'A', 'A', 'A', 'A', 'A'])

{'A': 7, 'B': 1, 'C': 1}

#### References for Task 1

LearnPython - Function
https://www.learnpython.org/en/Functions

Able.bio
https://able.bio/rhett/check-if-a-key-exists-in-a-python-dictionary--73iajoz#


___

#### Task 2

We need to create a function, called 'dicerolls', that will simulate rolling dice. There are two parameters of consideration that need to be reviewed. 

- Number of Dice: 'k'
- Number of times that the dice are rolled: 'n'

The aim of the function is to simulate the rolling of the dice, n times, and to keep track of the total of each face value. This should be stored in a disctionary, displaying the number of times each total face value happened.  
___

In [10]:
import numpy as np

In [32]:
# What's this doing?

rng = np.random.default_rng()

In [12]:
# and again
rng

Generator(PCG64) at 0x2996C7D0E50

In [13]:
 def dicerolls(dice, rolls):
    resultdict = {}
    rollresults = rng.integers(1, 7, size=rolls)
       
    for number in rollresults:
        if number in resultdict:
            resultdict[number] += 1
        else:
            resultdict[number] = 1
    return resultdict

In [88]:
# how to store an array inside an array 

def dicerolls(dice, rolls):
    resultdict = {}
    # print(rollresults)
    
    rollresults = []
    
    for x in range(0, dice):
        rollresults.append(rng.integers(1, 7, size=rolls))
      
    summedresults = []
    temparray = []
    temparray2 = []
    
    for x in range(0, dice):
        temparray = rollresults[x]
        temparray2 = summedresults + temparray
    print(summedresults)
     
    #for number in rollresults:
        #if number in resultdict:
            #resultdict[number] += 1
        #else:
           # resultdict[number] = 1
   # return resultdict

In [92]:
dicerolls(2, 1)

[]


In [17]:
d1 = np.random.random_integers(1, 6, 1000)
d2 = np.random.random_integers(1, 6, 1000)
dsums = d1 + d2

<ipython-input-17-8c19f05cb1d0>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  d1 = np.random.random_integers(1, 6, 1000)
<ipython-input-17-8c19f05cb1d0>:2: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  d2 = np.random.random_integers(1, 6, 1000)


In [81]:
d1 = np.random.randint(1, 6, 10)
print(d1)
d2 = np.random.randint(1, 6, 10)
print(d2)
dsums = d1 + d2

[1 1 1 4 1 2 3 2 3 4]
[1 1 3 2 4 2 3 5 5 2]


In [82]:
dsums

array([2, 2, 4, 6, 5, 4, 6, 7, 8, 6])

#### References for Task 2

Stack Overflow
https://stackoverflow.com/questions/45069108/use-list-as-function-definition-parameters-in-python

Old Refernece guide for Integers: 
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html#numpy.random.randint


___

#### Task 3

Create a program that will simulate the flipping of a coin 100 times. 
Then we need to run this simulation 1000 times, keeping track of the number of times the 'heads' value occurred. 

Once we know the value of these 1000 simulations, we need to plot these values leveraging the binomial distribution package. The plot should, if completely correctly, should take a bell-curve distribution, whereby the occurances of values greater or lesser than 50 are the points at which the likelihood decreases. 
___

In [20]:
n = 2
# Number of trials

In [21]:
p = 0.5
# probability of each event

In [22]:
Toss = rng.binomial(n, p, 50)

In [23]:
Toss

array([1, 2, 2, 2, 1, 1, 0, 0, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 0, 1, 2,
       1, 2, 0, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 2, 2, 1, 1, 2], dtype=int64)

In [29]:
sum(rng.binomial(n, p, 1) == 0) / 100

0.0

Explanation of work completed above: 



Notes: 
I dont understand the relationship between 1 & 100 versus 2 & 50

#### References for Task 3

Binomial Distribution Documentation
https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html

___

#### Task 4

Simpson’s paradox is a well-known statistical paradox where a trend evident in a number of groups reverses when the groups are combined into one big data set. Use numpy to create four data sets, each with an x array and a corresponding y array, to demonstrate Simpson’s paradox. You might create your x arrays using numpy.linspace and create the y array for each
x using notation like y = a * x + b where you choose the a and b for each x , y pair to demonstrate the paradox. 

___

#### References for Task 4


___

### Bibliography

LearnPython - Function
https://www.learnpython.org/en/Functions


Able.bio
https://able.bio/rhett/check-if-a-key-exists-in-a-python-dictionary--73iajoz#:~:text=To%20simply%20check%20if%20a,')%20%23%20Dogs%20found!&text=A%20dictionary%20can%20be%20a,counting%20the%20occurrence%20of%20items.

Stack Overflow
https://stackoverflow.com/questions/45069108/use-list-as-function-definition-parameters-in-python

Old Refernece guide for Integers: 
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html#numpy.random.randint
